## COLOR SCHEME
# add the following to your alacritty.toml
[colors.primary]
background = "#09090d"
foreground = "#e3c7fc"

[colors.cursor]
text = "#09090d"
cursor = "#f1c4e0"

[colors.vi_mode_cursor]
text = "#f1c4e0"
cursor = "#edeff0"

[colors.search.matches]
foreground = "#09090d"
background = "#f1c4e0"

[colors.search.focused_match]
foreground = "#09090d"
background = "#262440"

[colors.footer_bar]
foreground = "#09090d"
background = "#f1c4e0"

[colors.hints.start]
foreground = "#09090d"
background = "#8897F4"

[colors.hints.end]
foreground = "#09090d"
background = "#f1c4e0"

[colors.selection]
text = "#09090d"
background = "#f1c4e0"

[colors.normal]
black = "#140a1d"
red = "#B52A5B"
green = "#FF4971"
yellow = "#8897F4"
blue = "#bd93f9"
magenta = "#E9729D"
cyan = "#F18FB0"
white = "#f1c4e0"

[colors.bright]
black = "#a8899c"
red = "#B52A5B"
green = "#FF4971"
yellow = "#8897F4"
blue = "#bd93f9"
magenta = "#E9729D"
cyan = "#F18FB0"
white = "#f1c4e0"

[[colors.indexed_colors]]
index = 16
color = "#fab387"

[[colors.indexed_colors]]
index = 17
color = "#f5e0dc"
